### ISSUE TITLE
GeoFA model version 1.6

### ISSUE THREAD

**Issue by cfischer00** [OpenFKG/fkg-postgresql#119]
Change-script:
- [x] Versions-comment på schema
- [x] Implementér #114 
- [x] Implementér #115 
- [x] Implementér #116 
- [x] Implementér #117 
- [x] Implementér #118 
- [x] Implementér resultatet af kald view, trigger og index utilities

Model:
- [x] Versions-comment på schema
- [x] Opdatér model aht. #114 
- [x] Opdatér model aht. #115 
- [x] Opdatér model aht. #116 
- [x] Opdatér model aht. #117 
- [x] Opdatér model aht. #118 
- [x] Generér opdateret model-script (040_metadata.sql)
~- [ ] Tilret 060_fkg_utilities. NEJ der er tale om standard navne på FK~

Doc:
 - [x] Opdatér Specifikation
 - [x] Opdatér README.md
