### ISSUE TITLE
Ny struktur på facilitets-tabeller

### ISSUE THREAD

**Issue by cfischer00** [OpenFKG/fkg-postgresql#61]
t_5800_fac_pkt_t, 
t_5801_fac_fl_t,
t_5802_fac_li_t

Ændres som nedenfor beskrevet:

Facilitet_punkt (5800):
Her skal laves følgende database-ændringer:
 - [x] `#025: Feltet navn skal have længden 254, se side 128 i specifikation.`
 - [x] `#026: Feltet lang_beskr skal have længden 3000, se side 128 i specifikation.`
 - [x] `#027: Feltet uk_l_beskr skal have længden 3000, se side 128 i specifikation.`
 - [x] `#028: Feltet d_l_beskr skal have længden 3000, se side 128 i specifikation.`
 - [x] `#029: Feltet saeson_st ændres til tekststreng med længde 25. Pas på, det er udfyldt, se side 129 i specifikation.`
 - [x] `#030: Feltet saeson_sl ændres til tekststreng med længde 25. Pas på, det er udfyldt, se side 129 i specifikation.`
 - [x] `#031: Suppleres med feltet saeson_bem, se side 129 i specifikation.`
 - [x] `#032: Suppleres med feltet folder_k, se side 129 i specifikation.`
 - [x] `#033: Suppleres med feltet folder, se side 129 i specifikation.`
 - [x] `#034: Suppleres med feltet folde_link, se side 129 i specifikation.`
 - [x] `#035: Suppleres med feltet foto_link, se side 129 i specifikation.`
 - [x] ~`#036: Suppleres med feltet foto_link1, se side 129 i specifikation.`~ **Christian: fandtes allerede**
 - [x] ~`#037: Suppleres med feltet foto_link2, se side 129 i specifikation.`~ **Christian: fandtes allerede**
 - [x] `#038: Suppleres med feltet foto_link3, se side 129 i specifikation.`
 - [x] `#039: Suppleres med feltet geofafoto, se side 130.`
 - [x] `#040: Suppleres med feltet geofafoto1, se side 130.`
 - [x] `#041: Suppleres med feltet geofafoto2, se side 130.`
 - [x] `#042: Suppleres med feltet geofafoto3, se side 130.`
 - [x] `#043: Suppleres med feltet film_link, se side 130 i specifikation.` **Christian: Eksisterende filmlink omdøbt til film_link**
 - [x] `#044: Suppleres med feltet film_link1, se side 130 i specifikation.`
 - [x] `#045: Suppleres med feltet film_link2, se side 130 i specifikation.`
 - [x] `#046: Suppleres med feltet film_link3, se side 130 i specifikation.`
 - [x] `#047: Suppleres med feltet vejkode, se side 130 i specifikation.`
 - [x] `#048: Suppleres med feltet vejnavn, se side 130 i specifikation.`
 - [x] `#049: Suppleres med feltet cvf_vejkode, se side 130 i specifikation.`
 - [x] `#050: Suppleres med feltet husnr, se side 130 i specifikation.`
 - [x] `#051: Suppleres med feltet postnr, se side 130 i specifikation.`
 - [x] `#052: Suppleres med feltet postnr_by, se side 130 i specifikation.`
 - [x] `#053: Suppleres med feltet adr_id, se side 130 i specifikation.`
 - [x] `#054: Suppleres med feltet link1, se side 130 i specifikation.`
 - [x] `#055: Suppleres med feltet link2, se side 130 i specifikation.`
 - [x] `#056: Suppleres med feltet link3, se side 130 i specifikation.`
 - [x] `#057: Suppleres med den nye facilitetstype ”Badepunkt”, se side 132 i specifikation.`
 - [x] `#058: Begrebsdefinitionen for ”3012, Shelter” (se side 134) ændres fra:`Primitiv overdækket overnatningsmulighed. En shelter kan være alt fra nogle stolper og en presenning, over klassiske sheltere, til simple hytter med overnatningspladser. Åbne i en eller flere sider eller helt lukkede. Til:Primitiv overdækket overnatningsmulighed. En shelter kan være alt fra nogle stolper og en presenning, over klassiske sheltere, til simple hytter med overnatningspladser. Åbne i en eller flere sider.`

Facilitet_flade (5801):
 - [x] `#059: Feltet navn skal have længden 254, se side 137 i specifikation.`
 - [x] `#060: Feltet lang_beskr skal have længden 3000, se side 137 i specifikation.`
 - [x] `#061: Feltet uk_l_beskr skal have længden 3000, se side 137 i specifikation.`
 - [x] `#062: Feltet d_l_beskr skal have længden 3000, se side 137 i specifikation.`
 - [x] `#063: Feltet saeson_st ændres til tekststreng med længde 25. Pas på, det er udfyldt, se side 138 i specifikation.`
 - [x] `#064: Feltet saeson_sl ændres til tekststreng med længde 25. Pas på, det er udfyldt, se side 138 i specifikation.`
 - [x] `#065: Suppleres med feltet saeson_bem, se side 138 i specifikation.`
 - [x] `#066: Suppleres med feltet folder_k, se side 138 i specifikation.`
 - [x] `#067: Suppleres med feltet folder, se side 138 i specifikation.`
 - [x] `#068: Suppleres med feltet folde_link, se side 138 i specifikation.`
 - [x] `#069: Suppleres med feltet foto_link, se side 138 i specifikation.`
 - [x] ~`#070: Suppleres med feltet foto_link1, se side 138 i specifikation.`~ **Christian: fandtes allerede**
 - [x] ~`#071: Suppleres med feltet foto_link2, se side 138 i specifikation.`~ **Christian: fandtes allerede**
 - [x] `#072: Suppleres med feltet foto_link3, se side 138 i specifikation.`
 - [x] `#073: Suppleres med feltet geofafoto, se side 138 i specifikation.`
 - [x] `#074: Suppleres med feltet geofafoto1, se side 138 i specifikation.`
 - [x] `#075: Suppleres med feltet geofafoto2, se side 138 i specifikation.`
 - [x] `#076: Suppleres med feltet geofafoto3, se side 139 i specifikation.`
 - [x] `#077: Suppleres med feltet film_link, se side 139 i specifikation.` **Christian: Eksisterende filmlink omdøbt til film_link**
 - [x] `#078: Suppleres med feltet film_link1, se side 139 i specifikation.`
 - [x] `#079: Suppleres med feltet film_link2, se side 139 i specifikation.`
 - [x] `#080: Suppleres med feltet film_link3, se side 139 i specifikation.`
 - [x] `#081: Suppleres med feltet vejkode, se side 139 i specifikation.`
 - [x] `#082: Suppleres med feltet vejnavn, se side 139 i specifikation.`
 - [x] `#083: Suppleres med feltet cvf_vejkode, se side 139 i specifikation.`
 - [x] `#084: Suppleres med feltet husnr, se side 139 i specifikation.`
 - [x] `#085: Suppleres med feltet postnr, se side 139 i specifikation.`
 - [x] `#086: Suppleres med feltet postnr_by, se side 139 i specifikation.`
 - [x] `#087: Suppleres med feltet adr_id, se side 139 i specifikation.`
 - [x] `#088: Suppleres med feltet link1, se side 139 i specifikation.`
 - [x] `#089: Suppleres med feltet link2, se side 139 i specifikation.`
 - [x] `#090: Suppleres med feltet link3, se side 139 i specifikation.`

Facilitet_linje (5802):
 - [x] `#091: Feltet navn skal have længden 254, se side 140 i specifikation.`
 - [x] `#092: Feltet laengde skal kun vises med 2 decimaler, se side 140 i specifikation.`
 - [x] `#093: Feltet lang_beskr skal have længden 3000, se side 141 i specifikation.`
 - [x] `#094: Feltet uk_l_beskr skal have længden 3000, se side 141 i specifikation.`
 - [x] `#095: Feltet d_l_beskr skal have længden 3000, se side 141 i specifikation.`
 - [x] `#096: Suppleres med feltet saeson_k, se side 141 i specifikation.`
 - [x] `#097: Suppleres med feltet saeson, se side 141 i specifikation.`
 - [x] `#098: Suppleres med feltet saeson_st, se side 141 i specifikation.`
 - [x] `#099: Suppleres med feltet saeson_sl, se side 142 i specifikation.`
 - [x] `#100: Suppleres med feltet saeson_bem, se side 142 i specifikation.`
 - [x] `#101: Feltet folder_k ændres i specifikation, se side 142 i specifikation.`
 - [x] `#102: Suppleres med feltet foto_link, se side 143 i specifikation.`
 - [x] ~`#103: Suppleres med feltet foto_link1, se side 143 i specifikation.`~ **Christian: fandtes allerede**
 - [x] ~`#104: Suppleres med feltet foto_link2, se side 143 i specifikation.`~ **Christian: fandtes allerede**
 - [x] `#105: Suppleres med feltet foto_link3, se side 143 i specifikation.`
 - [x] `#106: Suppleres med feltet geofafoto, se side 143 i specifikation.`
 - [x] `#107: Suppleres med feltet geofafoto1, se side 143 i specifikation.`
 - [x] `#108: Suppleres med feltet geofafoto2, se side 143 i specifikation.`
 - [x] `#109: Suppleres med feltet geofafoto3, se side 143 i specifikation.`
 - [x] `#110: Suppleres med feltet film_link, se side 143 i specifikation.`**Christian: Eksisterende filmlink omdøbt til film_link**
 - [x] `#111: Suppleres med feltet film_link1, se side 143 i specifikation.`
 - [x] `#112: Suppleres med feltet film_link2, se side 143 i specifikation.`
 - [x] `#113: Suppleres med feltet film_link3, se side 143 i specifikation.`
 - [x] `#114: Suppleres med feltet vejkode, se side 143 i specifikation.`
 - [x] `#115: Suppleres med feltet vejnavn, se side 143 i specifikation.`
 - [x] `#116: Suppleres med feltet cvf_vejkode, se side 143 i specifikation.`
 - [x] `#117: Suppleres med feltet husnr, se side 143 i specifikation.`
 - [x] `#118: Suppleres med feltet postnr, se side 143 i specifikation.`
 - [x] `#119: Suppleres med feltet postnr_by, se side 143 i specifikation.`
 - [x] `#120: Suppleres med feltet adr_id, se side 143 i specifikation.`
 - [x] `#121: Suppleres med feltet link1, se side 143 i specifikation.`
 - [x] `#122: Suppleres med feltet link2, se side 143 i specifikation.`
 - [x] `#123: Suppleres med feltet link3, se side 143 i specifikation.`
 - [x] `#124: Begrebsdefinitionen for ”9, Sejlrute” (se side 145) ændres fra:`Afmærket eller uafmærket rute for kano- og kajak-sejlads. Til: Afmærket eller beskrevet rute for kano- og kajak-sejlads.`
